### ISSUE TITLE
Unity 5.6 version release date

### ISSUE THREAD

**Issue by kotrs** [dotBunny/VSCode#150]
This plugin is very good. 
But the version 2.8 is not compatible with Unity 5.6. 
When will you release new version?
Thank you

**Comment by reapazor** [comment]
Hmm, whats not working in 5.6?

**Comment by kotrs** [comment]
There is no option for VSCode in Unity - Preferencies. So I am not able to switch on the plugin.

**Comment by reapazor** [comment]
Do you have compile errors in your project?

**Comment by kotrs** [comment]
Oh ... yes ... I have ... This is the issue ?

**Comment by reapazor** [comment]
Because the plugin is open source, the code needs to be compiled to be utilized. At least for the 'first time'. When unity runs into compilation errors it doesn't update any libraries loaded.

While we've contemplated providing a compiled build, people still seem to like the open source nature of the project :)

**Comment by kotrs** [comment]
It is working now ... thank you
